-- LEGION_COMMANDER_START
{
  legcom = {
    footprintx = 2,
    footprintz = 2,
    canresurrect = true,
    energymake = 50,
    metalmake = 5,
    health = 6000,
    autoheal = 40,
    buildoptions = {
      'legsolar',
      'legwin',
      'legmstor',
      'legestor',
      'legmex',
      'legeconv',
      'legnanotc',
      'legrezbot',
      'leglab',
      'legvp',
      'legap',
      'legdtl',
      'legdtf',
      'legdtr',
      'legjam',
      
    },
    customparams = {
      evolution_target = 'legcomlvl2',
      evolution_condition = 'timer_global',
      evolution_timer = 420,
    },
    weapondefs = {
      legcomlaser = {
        corethickness = 0.25,
        duration = 0.09,
        name = 'Light close-quarters g2g/g2a laser',
        range = 360,
        reloadtime = 0.20,
        rgbcolor = '0 2 1',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrcrw1',
        soundtrigger = true,
        sprayangle = 700,
        thickness = 6,
        texture1 = 'shot',
        texture2 = 'empty',
        weapontype = 'LaserCannon',
        weaponvelocity = 2100,
        damage = {
          default = 250,
        },
      },
      shotgun = {
        areaofeffect = 60,
        energypershot = 0,
        avoidfeature = false,
        craterboost = 0,
        cratermult = 0,
        cameraShake = 0,
        edgeeffectiveness = 0.65,
        explosiongenerator = 'custom:genericshellexplosion-small',
        impulseboost = 0.2,
        impulsefactor = 0.2,
        intensity = 3,
        name = '6 Gauge Shotgun',
        noselfdamage = true,
        predictboost = 1,
        projectiles = 6,
        range = 320,
        reloadtime = 2,
        rgbcolor = '1 0.75 0.25',
        size = 2,
        soundhit = 'xplomed2xs',
        soundhitwet = 'splsmed',
        soundstart = 'kroggie2xs',
        soundstartvolume = 12,
        sprayangle = 2000,
        turret = true,
        commandfire = true,
        weapontimer = 1,
        weapontype = 'Cannon',
        weaponvelocity = 600,
        stockpile = true,
        stockpiletime = 5,
        customparams = {
          stockpilelimit = 10,
        },
        damage = {
          default = 1800,
          commanders = 0,
        },
      },
    },
    weapons = {
      [3] = {
        def = 'shotgun',
        onlytargetcategory = 'SURFACE',
      },
    },
  }
}
-- LEGION_COMMANDER_END
