-- CORTEX_COMMANDER_LVL2_START
{
  corcomlvl2 = {
    footprintx = 2,
    footprintz = 2,
    speed = 62,
    health = 8500,
    energymake = 315,
    metalmake = 30,
    autoheal = 300,
    builddistance = 200,
    workertime = 600,
    buildoptions = {
      'corsolar',
      'coradvsol',
      'corwin',
      'corgeo',
      'cormstor',
      'corestor',
      'cormex',
      'coruwmex',
      'corexp',
      'cormakr',
      'corcan',
      'correap',
      'corlab',
      'corvp',
      'corap',
      'corhp',
      'cornanotc',
      'coreyes',
      'corrad',
      'cordrag',
      'cormaw',
      'corllt',
      'corhllt',
      'corhlt',
      'corpun',
      'corrl',
      'cormadsam',
      'corerad',
      'cordl',
      'corjamt',
      'corjuno',
      'corsy',
      'coruwgeo',
      'corfasp',
      'cornerco',
      'coruwes',
      'corplat',
      'corfhp',
      'coruwms',
      'corfhlt',
      'cornanotct2',
      'corfmkr',
      'cortide',
      'corfrad',
      'corfrt',
      'corfdrag',
      'cortl',
      'cornecro',
    },
    customparams = {
      evolution_target = 'corcomlvl3',
      evolution_condition = 'timer_global',
      evolution_timer = 1320,
      shield_power = 500,
      shield_radius = 100,
    },
    weapondefs = {
      armcomlaser = {
        areaofeffect = 16,
        avoidfeature = false,
        beamtime = 0.1,
        corethickness = 0.1,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        cylindertargeting = 1,
        edgeeffectiveness = 1,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        laserflaresize = 7.7,
        name = 'Light close-quarters g2g/g2a laser',
        noselfdamage = true,
        range = 500,
        reloadtime = 0.4,
        rgbcolor = '0.6 0.3 0.8',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrfir1',
        soundtrigger = 1,
        targetmoveerror = 0.05,
        thickness = 4,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 900,
        damage = {
          bombers = 180,
          default = 1500,
          fighters = 110,
          subs = 5,
        },
      },
      disintegrator = {
        areaofeffect = 36,
        avoidfeature = false,
        avoidfriendly = false,
        avoidground = false,
        bouncerebound = 0,
        cegtag = 'dgunprojectile',
        commandfire = true,
        craterboost = 0,
        cratermult = 0.15,
        edgeeffectiveness = 0.15,
        energypershot = 500,
        explosiongenerator = 'custom:expldgun',
        firestarter = 100,
        firesubmersed = false,
        groundbounce = true,
        impulseboost = 0,
        impulsefactor = 0,
        name = 'Disintegrator',
        noexplode = true,
        noselfdamage = true,
        range = 250,
        reloadtime = 6,
        paralyzer = {},
        soundhit = 'xplomas2s',
        soundhitwet = 'sizzlexs',
        soundstart = 'disigun1',
        soundhitvolume = 36,
        soundstartvolume = 96,
        soundtrigger = true,
        tolerance = 10000,
        turret = true,
        waterweapon = true,
        weapontimer = 4.2,
        weapontype = 'DGun',
        weaponvelocity = 300,
        damage = {
          commanders = 0,
          default = 20000,
          raptors = 10000,
        },
      },
    },
    weapons = {
      [1] = {
        def = 'armcomlaser',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'DISINTEGRATOR',
        onlytargetcategory = 'NOTSUB',
      },
    },
  }
}
-- CORTEX_COMMANDER_LVL2_END
