-- ARMADA_COMMANDER_LVL4_START
{
  armcomlvl4 = {
    footprintx = 2,
    footprintz = 2,
    autoheal = 2213,
    builddistance = 500,
    canresurrect = true,
    energymake = 3112,
    health = 28000,
    speed = 82,
    metalmake = 86,
    workertime = 6200,
    buildoptions = {
      'armanni',
      'armpb',
      'armamb',
      'armmoho',
      'armuwmme',
      'armflak',
      'armmercury',
      'armgate',
      'armsd',
      'armfort',
      'armtarg',
      'armarad',
      'armamd',
      'armveil',
      'armuwadvms',
      'armuwadves',
      'armmmkr',
      'armuwmmm',
      'armavp',
      'armaap',
      'armalab',
      'armfflak',
      'armatl',
      'armkraken',
      'armbrtha',
      'armannit3',
      'armlwall',
      'armgatet3',
	    'armannit4',
	    'armnanotct3',
    },
    customparams = {
      evolution_target = 'armcomlvl5',
      evolution_condition = 'timer_global',
      evolution_timer = 2400,
    },
    weapondefs = {
      old_armsnipe_weapon = {
        areaofeffect = 72,
        avoidfeature = true,
        avoidfriendly = true,
        collidefeature = true,
        collidefriendly = false,
        corethickness = 0.75,
        craterareaofeffect = 0,
        craterboost = 0,
        commandfire = true,
        cratermult = 0,
        cegtag = 'railgun',
        duration = 0.12,
        edgeeffectiveness = 1,
        energypershot = 2000,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 100,
        impulseboost = 0.4,
        impulsefactor = 1,
        intensity = 1.4,
        name = 'Long-range g2g armor-piercing rifle',
        range = 1250,
        reloadtime = 0.5,
        rgbcolor = '0.4 0.1 0.7',
        rgbcolor2 = '0.4 0.1 0.7',
        soundhit = 'sniperhit',
        soundhitwet = 'sizzle',
        soundstart = 'sniper3',
        soundtrigger = true,
        stockpile = true,
        stockpiletime = 2,
        customparams = {
          stockpilelimit = 15,
        },
        texture1 = 'shot',
        texture2 = 'empty',
        thickness = 6,
        tolerance = 1000,
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 3000,
        damage = {
          commanders = 10,
          default = 45000,
        },
      },
      ata = {
        areaofeffect = 16,
        avoidfeature = false,
        beamtime = 1.25,
        collidefriendly = false,
        corethickness = 0.5,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        edgeeffectiveness = 0.30,
        energypershot = 7000,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 90,
        impulsefactor = 0,
        largebeamlaser = true,
        laserflaresize = 7,
        name = 'Heavy tachyon beam',
        noselfdamage = true,
        range = 1100,
        reloadtime = 15,
        rgbcolor = '1 0 1',
        scrollspeed = 5,
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'annigun1',
        soundtrigger = 1,
        texture3 = 'largebeam',
        thickness = 10,
        tilelength = 150,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 3100,
        damage = {
          commanders = 480,
          default = 48000,
        },
      },
      armcomlaser = {
        areaofeffect = 12,
        avoidfeature = false,
        beamtime = 0.1,
        corethickness = 0.1,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        cylindertargeting = 1,
        edgeeffectiveness = 1,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        laserflaresize = 7.7,
        name = 'Close-range laser',
        noselfdamage = true,
        range = 550,
        reloadtime = 0.5,
        rgbcolor = '0.659 0 1',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrcrw2',
        soundtrigger = 1,
        targetmoveerror = 0.05,
        thickness = 6,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 900,
        damage = {
          default = 1750,
          VTOL = 200,
        },
      },
    },
    weapons = {
      [1] = {
        def = 'armcomlaser',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'old_armsnipe_weapon',
        onlytargetcategory = 'NOTSUB',
      },
      [4] = {
        badtargetcategory = 'VTOL GROUNDSCOUT',
        def = 'ATA',
        onlytargetcategory = 'SURFACE',
      },
      [5] = {
        def = '',
      },
      [6] = {
        def = '',
      },
    },
  }
}
-- ARMADA_COMMANDER_LVL4_END
