-- LEGION_COMMANDER_LVL4_START
{
  legcomlvl4 = {
    footprintx = 2,
    footprintz = 2,
    canresurrect = true,
    energymake = 2280,
    metalmake = 64,
    speed = 100,
    builddistance = 500,
    workertime = 1700,
    autoheal = 4500,
    health = 53900,
    buildoptions = {
      'legdeflector',
      'legbombard',
      'legadvestore',
      'legmoho',
      'legadveconv',
      'legarad',
      'legajam',
      'legkeres',
      'legacluster',
      'legamstor',
      'legflak',
      'legabm',
      'legbastion',
      'legbastiont4',
      'legnanotct2',
      'legrwall',
      'leglab',
      'legvp',
      'legap',
      'legtarg',
      'legsd',
      'leglraa',
      'legdtl',
      'legdtf',
      'legministarfall',
      'legstarfall',
      'leggatet3',
      'legperdition',
      'legsilo',
      'legnanotct3',

    },
    customparams = {
      evolution_target = 'legcomlvl5',
      evolution_condition = 'timer_global',
      evolution_timer = 2400,
    },
    weapondefs = {
      machinegun = {
        accuracy = 80,
        areaofeffect = 10,
        avoidfeature = false,
        beamburst = true,
        beamdecay = 1,
        beamtime = 0.07,
        burst = 6,
        burstrate = 0.10667,
        camerashake = 0,
        corethickness = 0.35,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        edgeeffectiveness = 1,
        explosiongenerator = "custom:laserhit-medium-red",
        firestarter = 10,
        impulsefactor = 0,
        largebeamlaser = true,
        laserflaresize = 30,
        name = "Rapid-fire close quarters g2g armor-piercing laser",
        noselfdamage = true,
        pulsespeed = "q8",
        range = 1100,
        reloadtime = 0.50,
        rgbcolor = "0.7 0.3 1.0",
        rgbcolor2 = "0.8 0.6 1.0",
        soundhitdry = "",
        soundhitwet = "sizzle",
        soundstart = "lasfirerc",
        soundtrigger = 1,
        sprayangle = 500,
        targetborder = 0.2,
        thickness = 5.5,
        tolerance = 4500,
        turret = true,
        weapontype = "BeamLaser",
        weaponvelocity = 920,
        damage = {
          default = 1300,
          vtol = 180,
        },
      },
      shotgunarm = {
        areaofeffect = 112,
        commandfire = true,
        avoidfeature = false,
        craterboost = 0,
        cratermult = 0,
        cameraShake = 0,
        edgeeffectiveness = 0.65,
        explosiongenerator = "custom:genericshellexplosion-medium",
        impulsefactor = 0.8,
        intensity = 0.2,
        mygravity = 1,
        name = "GaussCannon",
        noselfdamage = true,
        predictboost = 1,
        projectiles = 20,
        range = 650,
        reloadtime = 1,
        rgbcolor = "0.8 0.4 1.0",
        size = 4,
        sizeDecay = 0.044,
        stages = 16,
        alphaDecay = 0.66,
        soundhit = "xplomed2xs",
        soundhitwet = "splsmed",
        soundstart = "kroggie2xs",
        sprayangle = 3500,
        tolerance = 6000,
        turret = true,
        waterweapon = true,
        weapontimer = 2,
        weapontype = "Cannon",
        weaponvelocity = 900,
        stockpile = true,
        stockpiletime = 2,
        customparams = {
          stockpilelimit = 50,
        },
        damage = {
          default = 10000,
          commanders = 0,
        },
      },
      exp_heavyrocket = {
        areaofeffect = 70,
        collidefriendly = 0,
        collidefeature = 0,
        cameraShake = 0,
        energypershot = 125,
        avoidfeature = 0,
        avoidfriendly = 0,
        burst = 4,
        burstrate = 0.3,
        cegtag = "missiletrailsmall-red",
        colormap = '0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008',
        craterboost = 0,
        craterareaofeffect = 0,
        cratermult = 0,
        dance = 24,
        edgeeffectiveness = 0.65,
        explosiongenerator = "custom:burnblack",
        firestarter = 70,
        flighttime = 1.05,
        flamegfxtime = 1,
        impulsefactor = 0.123,
        impactonly = 1,
        model = "catapultmissile.s3o",
        movingaccuracy = 600,
        name = "Raptor Boomer",
        noselfdamage = true,
        proximitypriority = nil,
        range = 700,
        reloadtime = 1,
        smoketrail = true,
        smokePeriod = 4,
        smoketime = 16,
        smokesize = 8.5,
        smokecolor = 0.5,
        size = 2,
        smokeTrailCastShadow = false,
        soundhit = "rockhit",
        soundhitwet = "splsmed",
        soundstart = "rapidrocket3",
        startvelocity = 165,
        rgbcolor = '1 0.25 0.1',
        texture1 = "null",
        texture2 = "smoketrailbar",
        trajectoryheight = 1,
        targetmoveerror = 0.2,
        turnrate = 5000,
        tracks = true,
        turret = true,
        allowNonBlockingAim = true,
        weaponacceleration = 660,
        weapontimer = 6,
        weapontype = "MissileLauncher",
        weaponvelocity = 950,
        wobble = 2000,
        damage = {
          default = 1300,
        },
        customparams = {
          exclude_preaim = true,
          overrange_distance = 777,
          projectile_destruction_method = "descend",
        },
      },
    },
    weapons = {
      [1] = {
        def = 'machinegun',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'shotgunarm',
        onlytargetcategory = 'WEAPON',
      },
      [5] = {
        def = 'exp_heavyrocket',
        onlytargetcategory = 'SURFACE',
      },
    },
  }
}
-- LEGION_COMMANDER_LVL4_END
