-- LEGION_COMMANDER_LVL3_START
{
  legcomlvl3 = {
    footprintx = 2,
    footprintz = 2,
    canresurrect = true,
    energymake = 1500,
    metalmake = 45,
    speed = 85,
    builddistance = 350,
    workertime = 1200,
    autoheal = 900,
    health = 26000,
    customparams = {
      evolution_target = 'legcomlvl4',
      evolution_condition = 'timer_global',
      evolution_timer = 1740,
    },
    buildoptions = {
      'legdeflector',
      'legfus',
      'legbombard',
      'legadvestore',
      'legmoho',
      'legadveconv',
      'legarad',
      'legajam',
      'legforti',
      'legacluster',
      'legamstor',
      'legflak',
      'legabm',
      'legbastion',
      'legdtr',
      'legdtf',
      'legrezbot',
      'legdtl',
      'leglab',
      'legvp',
      'legap',
      'legbastiont4',
      'legnanotct2',
      'legnanotct3',
      'legapopupdef',
    },
    weapondefs = {
      legcomlaser = {
        accuracy = 50,
        areaofeffect = 12,
        avoidfriendly = true,
        avoidfeature = true,
        collidefriendly = false,
        collidefeature = true,
        beamtime = 0.09,
        corethickness = 0.55,
        duration = 0.09,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 0,
        impulseboost = 0,
        impulsefactor = 0,
        name = 'Light close-quarters g2g/g2a laser',
        noselfdamage = true,
        range = 640,
        reloadtime = 0.2,
        rgbcolor = '0 0.2 0.8',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrcrw1',
        soundtrigger = true,
        sprayangle = 500,
        targetmoveerror = 0.05,
        thickness = 7,
        tolerance = 1000,
        texture1 = 'shot',
        texture2 = 'empty',
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 2500,
        damage = {
          bombers = 180,
          default = 650,
          fighters = 110,
          subs = 5,
        },
      },
      shotgun = {
        areaofeffect = 90,
        energypershot = 0,
        avoidfeature = false,
        craterboost = 0,
        cratermult = 0,
        cameraShake = 0,
        edgeeffectiveness = 0.65,
        explosiongenerator = 'custom:genericshellexplosion-small',
        impulseboost = 0.2,
        impulsefactor = 0.2,
        intensity = 3,
        name = '12 Gauge Shotgun',
        noselfdamage = true,
        predictboost = 1,
        projectiles = 7,
        range = 540,
        reloadtime = 2,
        rgbcolor = '1 0.75 0.25',
        size = 2.5,
        soundhit = 'xplomed2xs',
        soundhitwet = 'splsmed',
        soundstart = 'kroggie2xs',
        soundstartvolume = 12,
        sprayangle = 2500,
        turret = true,
        commandfire = true,
        weapontimer = 1,
        weapontype = 'Cannon',
        weaponvelocity = 600,
        stockpile = true,
        stockpiletime = 5,
        customparams = {
          stockpilelimit = 20,
        },
        damage = {
          default = 3200,
          commanders = 0,
        },
      },
    },
    weapons = {
      [1] = {
        def = 'legcomlaser',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'shotgun',
        onlytargetcategory = 'SURFACE',
      },
      [5] = {
        def = '',
      },
    },
  },
}
-- LEGION_COMMANDER_LVL3_END
