-- CORTEX_COMMANDER_LVL3_START
{
  corcomlvl3 = {
    footprintx = 2,
    footprintz = 2,
    speed = 88,
    health = 30000,
    energymake = 2180,
    metalmake = 49,
    autoheal = 1500,
    workertime = 1200,
    builddistance = 350,
    buildoptions = {
      'corfus',
      'corafus',
      'corageo',
      'corbhmth',
      'cormoho',
      'cormexp',
      'cormmkr',
      'coruwadves',
      'coruwadvms',
      'corarad',
      'corshroud',
      'corfort',
      'corlab',
      'cortarg',
      'corsd',
      'corgate',
      'cortoast',
      'corvipe',
      'cordoom',
      'corflak',
      'corscreamer',
      'corvp',
      'corfmd',
      'corap',
      'corint',
      'corplat',
      'corsy',
      'coruwmme',
      'coruwmmm',
      'corenaa',
      'corfdoom',
      'coratl',
      'coruwfus',
      'corjugg',
      'corshiva',
      'corsumo',
      'corgol',
      'corkorg',
      'cornanotc2plat',
      'cornanotct2',
      'cornecro',
      'cordoomt3',
      'corhllllt',
      'cormaw',
      'cormwall',
      'corgatet3',
      'legendary_bulwark',
      'cornanotct3',
    },
    customparams = {
      evolution_target = 'corcomlvl4',
      evolution_condition = 'timer_global',
      evolution_timer = 1740,
    },
    weapondefs = {
      corcomlaser = {
        areaofeffect = 12,
        avoidfeature = false,
        beamtime = 0.1,
        corethickness = 0.1,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        cylindertargeting = 1,
        edgeeffectiveness = 1,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        laserflaresize = 5.5,
        name = 'J7Laser',
        noselfdamage = true,
        range = 900,
        reloadtime = 0.4,
        rgbcolor = '0.7 0 1',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrfir1',
        soundtrigger = 1,
        targetmoveerror = 0.05,
        thickness = 3,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 900,
        damage = {
          default = 2000,
          subs = 5,
        },
      },
      disintegrator = {
        areaofeffect = 36,
        avoidfeature = false,
        avoidfriendly = false,
        avoidground = false,
        bouncerebound = 0,
        cegtag = 'dgunprojectile',
        commandfire = true,
        craterboost = 0,
        cratermult = 0.15,
        edgeeffectiveness = 0.15,
        energypershot = 500,
        explosiongenerator = 'custom:expldgun',
        firestarter = 100,
        firesubmersed = false,
        groundbounce = true,
        impulseboost = 0,
        impulsefactor = 0,
        name = 'Disintegrator',
        noexplode = true,
        noselfdamage = true,
        range = 250,
        reloadtime = 3,
        paralyzer = {},
        soundhit = 'xplomas2s',
        soundhitwet = 'sizzlexs',
        soundstart = 'disigun1',
        soundhitvolume = 36,
        soundstartvolume = 96,
        soundtrigger = true,
        size = 4,
        tolerance = 10000,
        turret = true,
        waterweapon = true,
        weapontimer = 4.2,
        weapontype = 'DGun',
        weaponvelocity = 300,
        damage = {
          commanders = 0,
          default = 20000,
          scavboss = 1000,
          raptors = 10000,
        },
      },
    },
    weapons = {
      [1] = {
        def = 'CORCOMLASER',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [5] = {
        def = '',
      },
    },
  },
}
-- CORTEX_COMMANDER_LVL3_END
