-- LEGION_COMMANDER_LVL2_START
{
  legcomlvl2 = {
    footprintx = 2,
    footprintz = 2,
    canresurrect = true,
    energymake = 400,
    metalmake = 20,
    speed = 62,
    autoheal = 200,
    builddistance = 200,
    workertime = 800,
    health = 12000,
    customparams = {
      evolution_target = 'legcomlvl3',
      evolution_condition = 'timer_global',
      evolution_timer = 1320,
    },
    buildoptions = {
      'legsolar',
      'legadvsol',
      'legwin',
      'legmstor',
      'legestor',
      'legmex',
      'legeconv',
      'legrezbot',
      'leglab',
      'legvp',
      'legap',
      'corhllt',
      'leggeo',
      'legnanotct2',
      'legjam',
      'legdtf',
      'legmg',
      'legrad',
      'legdtl',
      'legdtr',
      'legrhapsis',
    },
    weapondefs = {
      legcomlaser = {
        accuracy = 50,
        areaofeffect = 12,
        avoidfriendly = false,
        avoidfeature = false,
        collidefriendly = false,
        collidefeature = true,
        beamtime = 0.09,
        corethickness = 0.3,
        duration = 0.09,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        name = 'Light close-quarters g2g/g2a laser',
        noselfdamage = true,
        range = 500,
        reloadtime = 0.2,
        rgbcolor = '0 0.95 0.05',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrcrw1',
        soundtrigger = true,
        sprayangle = 500,
        targetmoveerror = 0.05,
        thickness = 7,
        tolerance = 1000,
        texture1 = 'shot',
        texture2 = 'empty',
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 2200,
        damage = {
          bombers = 180,
          default = 450,
          fighters = 110,
          subs = 5,
        },
      },
      shotgun = {
        areaofeffect = 65,
        energypershot = 0,
        avoidfeature = false,
        craterboost = 0,
        cratermult = 0,
        cameraShake = 0,
        edgeeffectiveness = 0.65,
        explosiongenerator = 'custom:genericshellexplosion-small',
        impulseboost = 0.2,
        impulsefactor = 0.2,
        intensity = 3,
        name = '12 Gauge Shotgun',
        noselfdamage = true,
        predictboost = 1,
        projectiles = 7,
        range = 440,
        reloadtime = 2,
        rgbcolor = '1 0.75 0.25',
        size = 2.5,
        soundhit = 'xplomed2xs',
        soundhitwet = 'splsmed',
        soundstart = 'kroggie2xs',
        soundstartvolume = 12,
        sprayangle = 2250,
        turret = true,
        commandfire = true,
        weapontimer = 1,
        weapontype = 'Cannon',
        weaponvelocity = 600,
        stockpile = true,
        stockpiletime = 5,
        customparams = {
          stockpilelimit = 15,
        },
        damage = {
          default = 2200,
          commanders = 0,
        },
      },
    },
    weapons = {
      [1] = {
        def = 'legcomlaser',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'shotgun',
        onlytargetcategory = 'SURFACE',
      },
    },
  }
}
-- LEGION_COMMANDER_LVL2_END
