-- CORTEX_COMMANDER_START
{
  corcom = {
    footprintx = 2,
    footprintz = 2,
    customparams = {
      evolution_target = 'corcomlvl2',
      evolution_condition = 'timer_global',
      evolution_timer = 420,
    },
    autoheal = 80,
    speed = 45,
    energymake = 75,
    metalmake = 6,
    health = 5500,
    buildoptions = {
      'corsolar',
      'coradvsol',
      'corwin',
      'cormstor',
      'corestor',
      'cormex',
      'corexp',
      'cormakr',
      'corlab',
      'corvp',
      'corap',
      'corhp',
      'coreyes',
      'corrad',
      'cordrag',
      'corllt',
      'corrl',
      'cordl',
      'corhllt',
      'corcan',
      'correap',
      'corlevlr',
      'corak',
      'cormaw',
      'corjamt',
      'cornecro',
      'cortide',
      'corsy',
      'corfhp',
      'coruwms',
      'coruwes',
      'coruwmex',
      'corfmkr',
      'corfdrag',
      'cortl',
      'corfrt',
      'corfrad',
      'corgeo',
      'coruwgeo',
    },
    weapondefs = {
      corcomlaser = {
        range = 370,
        damage = {
          bombers = 180,
          default = 260,
          fighters = 110,
          subs = 5,
        },
      },
      disintegrator = {
        energypershot = 1000,
        reloadtime = 8,
      },
    },
  }
}
-- CORTEX_COMMANDER_END
