-- CORTEX_COMMANDER_LVL4_START
{
  corcomlvl4 = {
    footprintx = 2,
    footprintz = 2,
    speed = 80,
    health = 50000,
    energymake = 2380,
    metalmake = 56,
    autoheal = 3550,
    workertime = 1800,
    builddistance = 500,
    buildoptions = {
      'corfus',
      'corafus',
      'corageo',
      'corbhmth',
      'cormoho',
      'cormexp',
      'cormmkr',
      'coruwadves',
      'coruwadvms',
      'corarad',
      'corshroud',
      'corfort',
      'corlab',
      'cortarg',
      'corsd',
      'corgate',
      'cortoast',
      'corvipe',
      'cordoom',
      'corflak',
      'corscreamer',
      'corvp',
      'corfmd',
      'corap',
      'corint',
      'corplat',
      'corsy',
      'coruwmme',
      'coruwmmm',
      'corenaa',
      'corfdoom',
      'coratl',
      'coruwfus',
      'corjugg',
      'corshiva',
      'corsumo',
      'corgol',
      'corkorg',
      'cornanotc2plat',
      'cornanotct2',
      'cornecro',
      'cordoomt3',
      'corhllllt',
      'cormaw',
      'cormwall',
      'corgatet3',
      'legendary_bulwark',
      'cornanotct3',
    },
    customparams = {
      evolution_target = 'corcomlvl5',
      evolution_condition = 'timer_global',
      evolution_timer = 2400,
      shield_power = 500,
      shield_radius = 100,
    },
    weapondefs = {
      CORCOMLASER = {
        areaofeffect = 12,
        avoidfeature = false,
        beamtime = 0.1,
        corethickness = 0.1,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        cylindertargeting = 1,
        edgeeffectiveness = 1,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        laserflaresize = 5.5,
        name = 'J7Laser',
        noselfdamage = true,
        range = 1000,
        reloadtime = 0.4,
        rgbcolor = '0.7 0 1',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrfir1',
        soundtrigger = 1,
        targetmoveerror = 0.05,
        thickness = 3,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 900,
        damage = {
          default = 2500,
          subs = 5,
        },
      },
      disintegratorxl = {
        areaofeffect = 105,
        avoidfeature = false,
        avoidfriendly = true,
        avoidground = false,
        burst = 1,
        burstrate = 0,
        bouncerebound = 0,
        cegtag = 'gausscannonprojectilexl',
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        commandfire = true,
        cameraShake = 0,
        edgeeffectiveness = 1,
        energypershot = 0,
        explosiongenerator = 'custom:burnblackbiggest',
        firestarter = 100,
        firesubmersed = false,
        gravityaffected = true,
        impulsefactor = 0,
        intensity = 4,
        name = 'Darkmatter Photon-Disruptor',
        noexplode = true,
        noselfdamage = true,
        range = 500,
        reloadtime = 1,
        rgbcolor = '0.7 0.3 1.0',
        size = 5.5,
        soundhit = 'xplomas2',
        soundhitwet = 'sizzlexs',
        soundstart = 'disigun1',
        soundtrigger = true,
        tolerance = 10000,
        turret = true,
        weapontimer = 4.2,
        weapontype = 'DGun',
        weaponvelocity = 505,
        damage = {
          commanders = 0,
          default = 20000,
          scavboss = 1000,
          raptors = 10000,
        },
      },
      corcomeyelaser = {
        allowNonBlockingAim = true,
        avoidfriendly = true,
        areaofeffect = 6,
        avoidfeature = false,
        beamtime = 0.033,
        camerashake = 0.1,
        collidefriendly = false,
        corethickness = 0.35,
        craterareaofeffect = 12,
        craterboost = 0,
        cratermult = 0,
        edgeeffectiveness = 1,
        energypershot = 0,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 90,
        firetolerance = 300,
        impulsefactor = 0,
        laserflaresize = 2,
        name = 'EyeLaser',
        noselfdamage = true,
        proximitypriority = 1,
        range = 870,
        reloadtime = 0.033,
        rgbcolor = '0 1 0',
        rgbcolor2 = '0.8 0 0',
        scrollspeed = 5,
        soundhitdry = 'flamhit1',
        soundhitwet = 'sizzle',
        soundstart = 'heatray3burn',
        soundstartvolume = 6,
        soundtrigger = 1,
        thickness = 2.5,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 1500,
        damage = {
          default = 185,
        },
      },
    },
    weapons = {
      [1] = {
        def = 'CORCOMLASER',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        badtargetcategory = 'VTOL',
        def = 'disintegratorxl',
        onlytargetcategory = 'SURFACE',
      },
      [6] = {
        def = '',
      },
      [5] = {
        badtargetcategory = 'VTOL GROUNDSCOUT',
        def = 'corcomeyelaser',
        onlytargetcategory = 'SURFACE',
      },
    },
  }
}
-- CORTEX_COMMANDER_LVL4_END
