-- ARMADA_COMMANDER_LVL2_START
{
  armcomlvl2 = {
    footprintx = 2,
    footprintz = 2,
    autoheal = 125,
    builddistance = 200,
    canresurrect = true,
    energymake = 315,
    health = 8125,
    speed = 57.5,
    metalmake = 30,
    workertime = 1700,
    buildoptions = {
      'armsolar',
      'armwin',
      'armmstor',
      'armestor',
      'armmex',
      'armmakr',
      'armgate',
      'armlab',
      'armvp',
      'armap',
      'armeyes',
      'armrad',
      'armdrag',
      'armllt',
      'armrl',
      'armdl',
      'armtide',
      'armuwms',
      'armuwes',
      'armuwmex',
      'armfmkr',
      'armsy',
      'armfdrag',
      'armtl',
      'armfrt',
      'armfrad',
      'armhp',
      'armfhp',
      'armadvsol',
      'armgeo',
      'armamex',
      'armlwall',
      'armnanotct2',
      'armclaw',
      'armbeamer',
      'armhlt',
      'armguard',
      'armferret',
      'armcir',
      'armjamt',
      'armjuno',
      'armsy',
      'armrectr',
    },
    customparams = {
      evolution_target = 'armcomlvl3',
      evolution_condition = 'timer_global',
      evolution_timer = 1320,
    },
    weapondefs = {
      armcomlaser = {
        areaofeffect = 16,
        avoidfeature = false,
        beamtime = 0.1,
        corethickness = 0.1,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        cylindertargeting = 1,
        edgeeffectiveness = 1,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        laserflaresize = 7.7,
        name = 'Light close-quarters g2g/g2a laser',
        noselfdamage = true,
        range = 425,
        reloadtime = 0.7,
        rgbcolor = '0 1 1',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrfir1',
        soundtrigger = 1,
        targetmoveerror = 0.05,
        thickness = 4,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 900,
        damage = {
          default = 950,
          VTOL = 150,
        },
      },
      old_armsnipe_weapon = {
        areaofeffect = 42,
        avoidfeature = true,
        avoidfriendly = true,
        collidefeature = true,
        collidefriendly = false,
        corethickness = 0.75,
        craterareaofeffect = 0,
        craterboost = 0,
        commandfire = true,
        cratermult = 0,
        cegtag = 'railgun',
        duration = 0.12,
        edgeeffectiveness = 0.85,
        energypershot = 700,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 100,
        impulseboost = 0.4,
        impulsefactor = 1,
        intensity = 1,
        name = 'Long-range g2g armor-piercing rifle',
        range = 700,
        reloadtime = 1,
        rgbcolor = '0.2 0.1 1',
        rgbcolor2 = '0.2 0.1 1',
        soundhit = 'sniperhit',
        soundhitwet = 'sizzle',
        soundstart = 'sniper3',
        soundtrigger = true,
        stockpile = true,
        stockpiletime = 6,
        customparams = {
          stockpilelimit = 10,
        },
        texture1 = 'shot',
        texture2 = 'empty',
        thickness = 4,
        tolerance = 1000,
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 3000,
        damage = {
          commanders = 10,
          default = 11000,
        },
      },
    },
    weapons = {
      [1] = {
        def = 'armcomlaser',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'old_armsnipe_weapon',
        onlytargetcategory = 'NOTSUB',
      },
    },
  }
}
-- ARMADA_COMMANDER_LVL2_END
