-- ARMADA_COMMANDER_LVL3_START
{
  armcomlvl3 = {
    footprintx = 2,
    footprintz = 2,
    autoheal = 600,
    builddistance = 350,
    canresurrect = true,
    energymake = 2712,
    health = 16000,
    speed = 71.5,
    metalmake = 62,
    workertime = 3400,
    buildoptions = {
      'armanni',
      'armpb',
      'armamb',
      'armmoho',
      'armuwmme',
      'armflak',
      'armmercury',
      'armgate',
      'armsd',
      'armfort',
      'armtarg',
      'armarad',
      'armamd',
      'armveil',
      'armuwadvms',
      'armuwadves',
      'armmmkr',
      'armuwmmm',
      'armavp',
      'armaap',
      'armalab',
      'armfflak',
      'armatl',
      'armkraken',
      'armbrtha',
      'armannit3',
      'armlwall',
      'armgatet3',
      'armannit4',
      'armnanotct2',
      'armnanotct3',
    },
    customparams = {
      evolution_target = 'armcomlvl4',
      evolution_condition = 'timer_global',
      evolution_timer = 1740,
    },
    weapondefs = {
      old_armsnipe_weapon = {
        areaofeffect = 64,
        avoidfeature = true,
        avoidfriendly = true,
        collidefeature = true,
        collidefriendly = false,
        corethickness = 0.75,
        craterareaofeffect = 0,
        craterboost = 0,
        commandfire = true,
        cratermult = 0,
        cegtag = 'railgun',
        duration = 0.12,
        edgeeffectiveness = 1,
        energypershot = 2000,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 100,
        impulseboost = 0.4,
        impulsefactor = 1,
        intensity = 1.4,
        name = 'Long-range g2g armor-piercing rifle',
        range = 1250,
        reloadtime = 0.5,
        rgbcolor = '0.4 0.1 0.7',
        rgbcolor2 = '0.4 0.1 0.7',
        soundhit = 'sniperhit',
        soundhitwet = 'sizzle',
        soundstart = 'sniper3',
        soundtrigger = true,
        stockpile = true,
        stockpiletime = 3,
        customparams = {
          stockpilelimit = 10,
        },
        texture1 = 'shot',
        texture2 = 'empty',
        thickness = 6,
        tolerance = 1000,
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 3000,
        damage = {
          commanders = 10,
          default = 35000,
        },
      },
      armcomlaser = {
        areaofeffect = 12,
        avoidfeature = false,
        beamtime = 0.1,
        corethickness = 0.1,
        craterareaofeffect = 0,
        craterboost = 0,
        cratermult = 0,
        cylindertargeting = 1,
        edgeeffectiveness = 1,
        explosiongenerator = 'custom:laserhit-small-red',
        firestarter = 70,
        impactonly = 1,
        impulseboost = 0,
        impulsefactor = 0,
        laserflaresize = 7.7,
        name = 'Light close-quarters g2g/g2a laser',
        noselfdamage = true,
        range = 500,
        reloadtime = 0.6,
        rgbcolor = '0.1 0 1',
        soundhitdry = '',
        soundhitwet = 'sizzle',
        soundstart = 'lasrcrw2',
        soundtrigger = 1,
        targetmoveerror = 0.05,
        thickness = 6,
        tolerance = 10000,
        turret = true,
        weapontype = 'BeamLaser',
        weaponvelocity = 900,
        damage = {
          default = 1450,
          VTOL = 180,
        },
      },
    },
    weapons = {
      [5] = {
        badtargetcategory = 'MOBILE',
        def = 'armcomlaser',
        onlytargetcategory = 'NOTSUB',
        fastautoretargeting = true,
      },
      [3] = {
        def = 'old_armsnipe_weapon',
        onlytargetcategory = 'NOTSUB',
      },
      [4] = {
        def = '',
      },
      [1] = {
        def = '',
      },
      [6] = {
        def = '',
      },
    },
  },
}
-- ARMADA_COMMANDER_LVL3_END
