-- ARMADA_COMMANDER_START
{
  armcom = {
    footprintx = 2,
    footprintz = 2,
    customparams = {
      evolution_target = 'armcomlvl2',
      evolution_condition = 'timer_global',
      evolution_timer = 420,
    },
    energymake = 100,
    metalmake = 10,
    autoheal = 55,
    health = 4500,
    speed = 41,
    canresurrect = true,
    buildoptions = {
      'armsolar',
      'armwin',
      'armmstor',
      'armestor',
      'armmex',
      'armmakr',
      'armgate',
      'armlab',
      'armnanotc',
      'armvp',
      'armap',
      'armeyes',
      'armrad',
      'armdrag',
      'armllt',
      'armrl',
      'armdl',
      'armtide',
      'armuwms',
      'armuwes',
      'armuwmex',
      'armfmkr',
      'armsy',
      'armfdrag',
      'armtl',
      'armfrt',
      'armfrad',
      'armhp',
      'armfhp',
      'armgeo',
      'armamex',
      'armbeamer',
      'armjamt',
      'armsy',
      'armrectr',
      'armclaw',
    },
    weapondefs = {
      armcomlaser = {
        range = 330,
        rgbcolor = '0.7 1 1',
        soundstart = 'lasrfir1',
        damage = {
          default = 175,
        },
      },
      old_armsnipe_weapon = {
        areaofeffect = 32,
        avoidfeature = true,
        avoidfriendly = true,
        collidefeature = true,
        collidefriendly = false,
        corethickness = 0.75,
        craterareaofeffect = 0,
        craterboost = 0,
        commandfire = true,
        cratermult = 0,
        cegtag = 'railgun',
        duration = 0.12,
        edgeeffectiveness = 0.85,
        energypershot = 400,
        explosiongenerator = 'custom:laserhit-large-blue',
        firestarter = 100,
        impulseboost = 0.4,
        impulsefactor = 1,
        intensity = 0.8,
        name = 'Long-range rail rifle',
        range = 550,
        reloadtime = 1,
        rgbcolor = '0 1 1',
        rgbcolor2 = '0 1 1',
        soundhit = 'sniperhit',
        soundhitwet = 'sizzle',
        soundstart = 'sniper3',
        soundtrigger = true,
        stockpile = true,
        stockpiletime = 7,
        customparams = {
          stockpilelimit = 5,
        },
        texture1 = 'shot',
        texture2 = 'empty',
        thickness = 4,
        tolerance = 1000,
        turret = true,
        weapontype = 'LaserCannon',
        weaponvelocity = 3000,
        damage = {
          commanders = 100,
          default = 4900,
        },
      },
    },
    weapons = {
      [3] = {
        def = 'old_armsnipe_weapon',
        onlytargetcategory = 'NOTSUB',
      },
    },
  }
}
-- ARMADA_COMMANDER_END
